Finds the Magnitude of a Vector
andrefpoliveira/Pansy pull request #35
Opened 2020-10-18 21:40 UTC by Shreyas-OwO

Hello @andrefpoliveira!

This program is a contribution to the collection of the example programs is the  ``examples`` directory.

This program defines a function which calculates and returns the magnitude of a vector whose direction ratios are put in a list and passed to it (the defined function).

Also, it would be helpful to me if you could add ``hacktoberfest-accepted`` label to this PR.

Thanks! :smile:

2020-10-19 08:44 UTC, andrefpoliveira requested changes

2020-10-19 08:44 UTC, andrefpoliveira commented on examples/VectorMagnitude/README.md
> +Argument #1 - Type: Integer/Float
@Shreyas-OwO first of all, thank you for your contribution!
This first argument is actually a list of integer/floats 😄 Could you please fix it please?

2020-10-19 19:16 UTC, Shreyas-OwO commented on examples/VectorMagnitude/README.md
> +Argument #1 - Type: Integer/Float
Done!

2020-10-19 19:17 UTC, Shreyas-OwO commented
Hello @andrefpoliveira! The suggested changes have been made.

2020-10-22 07:30 UTC, andrefpoliveira approved these changes
Thanks!!

2020-10-22 07:30 UTC, merged